#!/usr/bin/env bash
set -euo pipefail

export TI_ROOT="${TI_ROOT:-/opt/ti}"
export MMWAVE_SDK_ROOT="${MMWAVE_SDK_ROOT:-$TI_ROOT/mmwave_sdk_03_06_02_00-LTS}"
export MMWAVE_SDK_PACKAGES="${MMWAVE_SDK_PACKAGES:-$MMWAVE_SDK_ROOT/packages}"
export MMWAVE_SDK_INSTALL_PATH="$MMWAVE_SDK_PACKAGES"
export MMWAVE_SDK_TOOLS_INSTALL_PATH="$TI_ROOT"
export MMWAVE_SDK_DEVICE="${MMWAVE_SDK_DEVICE:-iwr68xx}"
export MMWAVE_SDK_DEVICE_TYPE="${MMWAVE_SDK_DEVICE_TYPE:-xwr68xx}"

export R4F_CODEGEN_ROOT="${R4F_CODEGEN_ROOT:-$TI_ROOT/ti-cgt-arm_16.9.6.LTS}"
export C674_CODEGEN_ROOT="${C674_CODEGEN_ROOT:-$TI_ROOT/ti-cgt-c6000_8.3.3}"
export XDC_ROOT="${XDC_ROOT:-$TI_ROOT/xdctools_3_50_08_24_core}"
export BIOS_ROOT="${BIOS_ROOT:-$TI_ROOT/bios_6_73_01_01}"
export DSPLIB_C64PX_ROOT="${DSPLIB_C64PX_ROOT:-$TI_ROOT/dsplib_c64Px_3_4_0_0}"
export DSPLIB_C674X_ROOT="${DSPLIB_C674X_ROOT:-$TI_ROOT/dsplib_c674x_3_4_0_0}"
export MATHLIB_C674X_ROOT="${MATHLIB_C674X_ROOT:-$TI_ROOT/mathlib_c674x_3_1_2_1}"

export R4F_CODEGEN_INSTALL_PATH="$R4F_CODEGEN_ROOT"
export C674_CODEGEN_INSTALL_PATH="$C674_CODEGEN_ROOT"
export XDC_INSTALL_PATH="$XDC_ROOT"
export BIOS_INSTALL_PATH="$BIOS_ROOT/packages"
export C64Px_DSPLIB_INSTALL_PATH="$DSPLIB_C64PX_ROOT"
export C674x_DSPLIB_INSTALL_PATH="$DSPLIB_C674X_ROOT"
export C674x_MATHLIB_INSTALL_PATH="$MATHLIB_C674X_ROOT"

export PATH="$R4F_CODEGEN_ROOT/bin:$C674_CODEGEN_ROOT/bin:$XDC_ROOT:$PATH"

case "${1:-}" in
  --print)
    env | grep -E '^(TI_ROOT|MMWAVE|R4F|C674|XDC|BIOS|DSPLIB|MATHLIB)=' | sort
    ;;
  --cmake-args)
    printf '%q ' \
      "-DTI_ROOT=$TI_ROOT" \
      "-DMMWAVE_SDK_PACKAGES=$MMWAVE_SDK_PACKAGES" \
      "-DR4F_CODEGEN_ROOT=$R4F_CODEGEN_ROOT" \
      "-DC674_CODEGEN_ROOT=$C674_CODEGEN_ROOT" \
      "-DXDC_ROOT=$XDC_ROOT" \
      "-DBIOS_ROOT=$BIOS_ROOT" \
      "-DDSPLIB_C64PX_ROOT=$DSPLIB_C64PX_ROOT" \
      "-DDSPLIB_C674X_ROOT=$DSPLIB_C674X_ROOT" \
      "-DMATHLIB_C674X_ROOT=$MATHLIB_C674X_ROOT"
    printf '\n'
    ;;
esac
