if(NOT DEFINED XS_EXE)
    message(FATAL_ERROR "XS_EXE is required")
endif()
if(NOT DEFINED BIOS_PACKAGES)
    message(FATAL_ERROR "BIOS_PACKAGES is required")
endif()
if(NOT DEFINED MMWAVE_SDK_PACKAGES)
    message(FATAL_ERROR "MMWAVE_SDK_PACKAGES is required")
endif()
if(NOT DEFINED CFG_FILE)
    message(FATAL_ERROR "CFG_FILE is required")
endif()
if(NOT DEFINED OUT_DIR)
    message(FATAL_ERROR "OUT_DIR is required")
endif()
if(NOT DEFINED TARGET_NAME)
    message(FATAL_ERROR "TARGET_NAME is required")
endif()
if(NOT DEFINED PLATFORM_NAME)
    message(FATAL_ERROR "PLATFORM_NAME is required")
endif()
if(NOT DEFINED CODEGEN_ROOT)
    message(FATAL_ERROR "CODEGEN_ROOT is required")
endif()
if(NOT DEFINED CORE)
    message(FATAL_ERROR "CORE is required")
endif()

string(CONCAT _xdcpath "${BIOS_PACKAGES}" ";" "${MMWAVE_SDK_PACKAGES}")
string(REPLACE ";" "\\;" _xdcpath_arg "${_xdcpath}")
set(ENV{XDCPATH} "${_xdcpath}")
set(ENV{MMWAVE_SDK_INSTALL_PATH} "${MMWAVE_SDK_PACKAGES}")
set(ENV{MMWAVE_SDK_DEVICE} "${MMWAVE_SDK_DEVICE}")
set(ENV{MMWAVE_SDK_DEVICE_TYPE} "${MMWAVE_SDK_DEVICE_TYPE}")

get_filename_component(_cfg_name "${CFG_FILE}" NAME)
set(_cfg_work_dir "${OUT_DIR}/configuro-input")
set(_cfg_work "${_cfg_work_dir}/${_cfg_name}")
file(MAKE_DIRECTORY "${_cfg_work_dir}")
configure_file("${CFG_FILE}" "${_cfg_work}" COPYONLY)

set(_extra_args "")
if(CORE STREQUAL "mss")
    set(_extra_args "--compileOptions \"--enum_type=int\"")
elseif(CORE STREQUAL "dss")
    set(_extra_args "-DMMWAVE_SDK_DEVICE=${MMWAVE_SDK_DEVICE}")
endif()

set(_bat "${OUT_DIR}/run_configuro.bat")
file(WRITE "${_bat}" "@echo off\n")
file(APPEND "${_bat}" "set \"XDCPATH=${_xdcpath}\"\n")
file(APPEND "${_bat}" "set \"MMWAVE_SDK_INSTALL_PATH=${MMWAVE_SDK_PACKAGES}\"\n")
file(APPEND "${_bat}" "set \"MMWAVE_SDK_DEVICE=${MMWAVE_SDK_DEVICE}\"\n")
file(APPEND "${_bat}" "set \"MMWAVE_SDK_DEVICE_TYPE=${MMWAVE_SDK_DEVICE_TYPE}\"\n")
file(APPEND "${_bat}" "\"${XS_EXE}\" \"--xdcpath=${_xdcpath}\" xdc.tools.configuro -t \"${TARGET_NAME}\" -p \"${PLATFORM_NAME}\" -r release -c \"${CODEGEN_ROOT}\" -DMMWAVE_SDK_DEVICE_TYPE=${MMWAVE_SDK_DEVICE_TYPE} ${_extra_args} -o \"${OUT_DIR}\" \"${_cfg_work}\"\n")

execute_process(
    COMMAND cmd /c "${_bat}"
    WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
    RESULT_VARIABLE _result
)

if(NOT _result EQUAL 0)
    message(FATAL_ERROR "xdc.tools.configuro failed with exit code ${_result}")
endif()
